ruby '>= 2.6'
source 'https://rubygems.org'

gem 'activesupport', '~> 6.1.7.5'
gem 'base64'
gem 'benchmark'
gem 'bigdecimal'
gem 'csv'
gem 'logger'
gem 'middleman', '~> 4.4'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'middleman-sprockets', '~> 4.1'
gem 'middleman-syntax', '~> 3.2'
gem 'mutex_m'
gem 'nokogiri', '~> 1.18.9'
gem 'ostruct'
gem 'rack', '~>2.2.22'
gem 'rdoc'
gem 'redcarpet', '~> 3.6.0'
gem 'rexml', '~> 3.4.2'
gem 'rouge', '~> 3.21'
gem 'sass'
gem 'webrick', '~> 1.8.2'